name: Luacheck
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Luacheck linter
      uses: lunarmodules/luacheck@master